import './globals.css'

export const metadata = {
  title: 'Training Programming Logic',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

        {children}

      </body>
    </html>
  )
}
