import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Training Programming Logic',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <div className='bg-teal-600 rounded-lg w-3/5 px-7 py-6'>
          <h1 className='text-zinc-300 text-xl font-semibold text-center'>
            Click on the buttons below to access their respective challenges!
          </h1>
        </div>

      </body>
    </html>
  )
}
