import './globals.css'

export const metadata = {
  title: 'Training Programming Logic',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='bg-teal-600 w-vw h-20'>

        </div>
        {children}

      </body>
    </html>
  )
}
